// CSS consumes Vuetify's generated variables: keep palette values here.
export const bistroThemes = {
  light: {
    dark: false,
    colors: {
      "background": "#f5efe1",
      "surface": "#fffaf0",
      "paper": "#f2e8d5",
      "surface-variant": "#e9dfcc",
      "on-background": "#302820",
      "on-surface": "#302820",
      "on-surface-variant": "#302820",
      "primary": "#a84c3f",
      "on-primary": "#fffaf0",
      "secondary": "#526246",
      "on-secondary": "#fffaf0",
      "accent": "#243447",
      "on-accent": "#fffaf0",
      "sage": "#78866b",
      "copper": "#b77945",
      "butter": "#e4bd64",
      "success": "#90db6a",
      "info": "#3c3e64",
      "warning": "#875510",
      "error": "#a93632",
      "on-success": "#fffaf0",
      "on-info": "#fffaf0",
      "on-warning": "#fffaf0",
      "on-error": "#fffaf0",
    },
  },
  dark: {
    dark: true,
    colors: {
      "background": "#211f1c",
      "surface": "#2c2924",
      "paper": "#2c2924",
      "surface-variant": "#423c33",
      "on-background": "#f5efe1",
      "on-surface": "#f5efe1",
      "on-surface-variant": "#f5efe1",
      "primary": "#a84c3f",
      "on-primary": "#302820",
      "secondary": "#b0c29f",
      "on-secondary": "#211f1c",
      "accent": "#b5cbe1",
      "on-accent": "#211f1c",
      "sage": "#a4b397",
      "copper": "#d4a476",
      "butter": "#e4bd64",
      "success": "#90db6a",
      "info": "#8ea9e0",
      "warning": "#e4bd64",
      "error": "#ffa49b",
      "on-success": "#211f1c",
      "on-info": "#211f1c",
      "on-warning": "#211f1c",
      "on-error": "#211f1c",
    },
  },
};
